curl http://media.sundog-soft.com/es8/movies.json > tmp/movies.json


### update a new index
PUT http://localhost:9200/movies
Content-Type: application/json

{
    "mappings": {
        "properties" : {
            "year": {"type":"date"}
        }
    }
}

### GET the new index
GET http://localhost:9200/movies/_mapping?pretty


### insert 
PUT http://localhost:9200/movies/_doc/109487
Content-Type: application/json

{
    "genre" : ["IMAX", "Sci-Fi"],
    "title": "Interstellar",
    "year": 2014
}

### GET the entire index
GET http://localhost:9200/movies/_search?pretty

