### Test that es is up
GET http://localhost:9200

###  download mappings (save to tmp folder)
GET http://media.sundog-soft.com/es8/shakes-mapping.json

### send mapping file
PUT http://localhost:9200/shakespeare
Content-Type: application/json

< tmp/shakes-mapping.json

### download documents (do this in bash)
curl http://media.sundog-soft.com/es8/shakespeare_8.0.json > tmp/shakespeare_8.0.json


### import the content 
PUT http://localhost:9200/shakespeare/_bulk 
Content-Type: application/json

< tmp/shakespeare_8.0.json

### search
GET http://localhost:9200/shakespeare/_search?pretty
Content-Type: application/json

{
    "query": {
        "match_phrase": { 
            "text_entry" :"to be or not to be"
        }
    }
}