### update a new index
PUT http://localhost:9200/movies
Content-Type: application/json

{
    "mappings": {
        "properties" : {
            "year": {"type":"date"}
        }
    }
}

### GET the index mapping
GET http://localhost:9200/movies/_mapping?pretty


### insert 
PUT http://localhost:9200/movies/_bulk
Content-Type: application/json

< tmp/movies.json



### GET all the data
GET http://localhost:9200/movies/_search?pretty

